---
#  Item_1 is name default, you can change name example like: nam, dragovn, ....
Item_1:
#----------------------------------------------------------
#  [Item id:meta,  Item count,  Id enchantment,  Level enchantment]     
#  if id & level = 0 -> enchantment not working !
#----------------------------------------------------------     
    shape:
    - [[0], ["260:0"], [0]]
    - [["260:0"], ["260:0"], ["260:0"]]
    - [[0], ["260:0"], [0]]    
    result:  ["278:0", 1, 17, 2]
...
